//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_phukien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string SoLienHe { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string VaiTro { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
